//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.ClienteDireccionEntrega = new HashSet<ClienteDireccionEntrega>();
            this.Molde = new HashSet<Molde>();
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int IdCliente { get; set; }
        public string RazonSocial { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string NombreContacto { get; set; }
        public string CUIT { get; set; }
        public int IdLocalidad { get; set; }
        public string Direccion { get; set; }
        public bool Activo { get; set; }
        public int IdUsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string CodigoPostal { get; set; }
        public int CodigoCliente { get; set; }
    
        public virtual Localidad Localidad { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<ClienteDireccionEntrega> ClienteDireccionEntrega { get; set; }
        public virtual ICollection<Molde> Molde { get; set; }
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
