//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteDireccionEntrega
    {
        public ClienteDireccionEntrega()
        {
            this.Despacho = new HashSet<Despacho>();
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int IdClienteDireccionEntrega { get; set; }
        public string Nombre { get; set; }
        public int IdCliente { get; set; }
        public int IdLocalidad { get; set; }
        public string Direccion { get; set; }
        public string CodigoPostal { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Localidad Localidad { get; set; }
        public virtual ICollection<Despacho> Despacho { get; set; }
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
