//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Despacho
    {
        public Despacho()
        {
            this.DespachoBulto = new HashSet<DespachoBulto>();
        }
    
        public int IdDespacho { get; set; }
        public int Numero { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdCliente { get; set; }
        public int IdClienteDireccionEntrega { get; set; }
        public int Cantidad { get; set; }
    
        public virtual ClienteDireccionEntrega ClienteDireccionEntrega { get; set; }
        public virtual ICollection<DespachoBulto> DespachoBulto { get; set; }
    }
}
