//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DespachoTerceroBultoRespuesta
    {
        public int IdDespachoTerceroBultoRespuesta { get; set; }
        public int IdDespachoTerceroRespuesta { get; set; }
        public int IdEmbalaje { get; set; }
        public Nullable<int> IdEmbalajeRespuesta { get; set; }
        public int CantidadIngreso { get; set; }
        public int Scrap { get; set; }
        public Nullable<int> IdPedidoProductoMedida { get; set; }
    
        public virtual DespachoTerceroRespuesta DespachoTerceroRespuesta { get; set; }
        public virtual Embalaje Embalaje { get; set; }
        public virtual Embalaje Embalaje1 { get; set; }
    }
}
