//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DespachoTercero
    {
        public DespachoTercero()
        {
            this.DespachoTerceroBulto = new HashSet<DespachoTerceroBulto>();
            this.DespachoTerceroRespuesta = new HashSet<DespachoTerceroRespuesta>();
        }
    
        public int IdDespachoTercero { get; set; }
        public int IdProceso { get; set; }
        public int Numero { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdProveedor { get; set; }
        public int CantidadEgreso { get; set; }
        public int CantidadIngreso { get; set; }
        public int ScrapTotal { get; set; }
    
        public virtual Proceso Proceso { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual ICollection<DespachoTerceroBulto> DespachoTerceroBulto { get; set; }
        public virtual ICollection<DespachoTerceroRespuesta> DespachoTerceroRespuesta { get; set; }
    }
}
