//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Embalaje
    {
        public Embalaje()
        {
            this.DespachoBulto = new HashSet<DespachoBulto>();
            this.DespachoTerceroBulto = new HashSet<DespachoTerceroBulto>();
            this.DespachoTerceroBultoRespuesta = new HashSet<DespachoTerceroBultoRespuesta>();
            this.DespachoTerceroBultoRespuesta1 = new HashSet<DespachoTerceroBultoRespuesta>();
            this.EmbalajeBulto = new HashSet<EmbalajeBulto>();
        }
    
        public int IdEmbalaje { get; set; }
        public int IdProceso { get; set; }
        public int Numero { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdCliente { get; set; }
        public int IdPedido { get; set; }
        public int Cantidad { get; set; }
        public Nullable<bool> Despachado { get; set; }
    
        public virtual ICollection<DespachoBulto> DespachoBulto { get; set; }
        public virtual ICollection<DespachoTerceroBulto> DespachoTerceroBulto { get; set; }
        public virtual ICollection<DespachoTerceroBultoRespuesta> DespachoTerceroBultoRespuesta { get; set; }
        public virtual ICollection<DespachoTerceroBultoRespuesta> DespachoTerceroBultoRespuesta1 { get; set; }
        public virtual Proceso Proceso { get; set; }
        public virtual ICollection<EmbalajeBulto> EmbalajeBulto { get; set; }
    }
}
