//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.EmpresaCai = new HashSet<EmpresaCai>();
            this.PuntoVenta = new HashSet<PuntoVenta>();
        }
    
        public int IdEmpresa { get; set; }
        public string RazonSocial { get; set; }
        public string CUIT { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public int IdProvincia { get; set; }
        public int IdLocalidad { get; set; }
        public string CodigoPostal { get; set; }
        public string IngresosBrutos { get; set; }
        public System.DateTime InicioActividad { get; set; }
    
        public virtual ICollection<EmpresaCai> EmpresaCai { get; set; }
        public virtual ICollection<PuntoVenta> PuntoVenta { get; set; }
    }
}
