//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaCai
    {
        public int IdEmpresaCai { get; set; }
        public int IdEmpresa { get; set; }
        public int IdPuntoVenta { get; set; }
        public string Numero { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual PuntoVenta PuntoVenta { get; set; }
    }
}
