//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsertoClase
    {
        public InsertoClase()
        {
            this.Inserto = new HashSet<Inserto>();
        }
    
        public int IdInsertoClase { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Inserto> Inserto { get; set; }
    }
}
