//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inyeccion
    {
        public Inyeccion()
        {
            this.InyeccionEstacion = new HashSet<InyeccionEstacion>();
        }
    
        public int IdInyeccion { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Numero { get; set; }
        public int IdInyectora { get; set; }
    
        public virtual ICollection<InyeccionEstacion> InyeccionEstacion { get; set; }
    }
}
