//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InyectoraOperario
    {
        public int IdInyectoraOperario { get; set; }
        public int IdInyectora { get; set; }
        public int Personas { get; set; }
        public decimal Horas { get; set; }
        public System.DateTime FechaJornada { get; set; }
        public System.DateTime HoraInicioJornada { get; set; }
        public decimal CantidadSuelas { get; set; }
    
        public virtual Inyectora Inyectora { get; set; }
    }
}
