//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InyeccionEstacionPedido
    {
        public InyeccionEstacionPedido()
        {
            this.InyeccionEstacionCajon = new HashSet<InyeccionEstacionCajon>();
        }
    
        public int IdInyeccionEstacionPedido { get; set; }
        public int IdInyeccionEstacion { get; set; }
        public Nullable<int> IdProgramacionPedidoProducto { get; set; }
        public Nullable<int> IdPedidoProductoMedida { get; set; }
        public decimal Scrap { get; set; }
    
        public virtual InyeccionEstacion InyeccionEstacion { get; set; }
        public virtual ICollection<InyeccionEstacionCajon> InyeccionEstacionCajon { get; set; }
        public virtual PedidoProductoMedida PedidoProductoMedida { get; set; }
        public virtual ProgramacionPedidoProducto ProgramacionPedidoProducto { get; set; }
    }
}
