//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inyectora
    {
        public Inyectora()
        {
            this.InyectoraEstacion = new HashSet<InyectoraEstacion>();
            this.InyectoraOperario = new HashSet<InyectoraOperario>();
            this.MaterialInyectora = new HashSet<MaterialInyectora>();
            this.MoldeInyectora = new HashSet<MoldeInyectora>();
        }
    
        public int IdInyectora { get; set; }
        public string Nombre { get; set; }
        public int CantidadMateriales { get; set; }
        public int CantidadEstaciones { get; set; }
        public Nullable<decimal> CantidadSuelas1 { get; set; }
        public Nullable<decimal> CantidadSuelas2 { get; set; }
        public Nullable<decimal> CantidadSuelas3 { get; set; }
        public Nullable<decimal> CantidadSuelas4 { get; set; }
        public Nullable<decimal> CantidadSuelas5 { get; set; }
        public Nullable<decimal> CantidadSuelas6 { get; set; }
        public bool Activo { get; set; }
        public int IdUsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public bool MoldeFinDia { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<InyectoraEstacion> InyectoraEstacion { get; set; }
        public virtual ICollection<InyectoraOperario> InyectoraOperario { get; set; }
        public virtual ICollection<MaterialInyectora> MaterialInyectora { get; set; }
        public virtual ICollection<MoldeInyectora> MoldeInyectora { get; set; }
    }
}
