//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InyeccionEstacion
    {
        public InyeccionEstacion()
        {
            this.InyeccionEstacionPedido = new HashSet<InyeccionEstacionPedido>();
        }
    
        public int IdInyeccionEstacion { get; set; }
        public int IdInyeccion { get; set; }
        public int IdInyectoraEstacion { get; set; }
        public int CantidadTotal { get; set; }
        public decimal ScrapTotal { get; set; }
    
        public virtual Inyeccion Inyeccion { get; set; }
        public virtual InyectoraEstacion InyectoraEstacion { get; set; }
        public virtual ICollection<InyeccionEstacionPedido> InyeccionEstacionPedido { get; set; }
    }
}
