//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.MaterialColor = new HashSet<MaterialColor>();
            this.MaterialInyectora = new HashSet<MaterialInyectora>();
            this.MaterialMateriaPrima = new HashSet<MaterialMateriaPrima>();
            this.ProductoMaterial = new HashSet<ProductoMaterial>();
        }
    
        public int IdMaterial { get; set; }
        public string Nombre { get; set; }
        public decimal DensidadEsperadaMin { get; set; }
        public decimal TiempoCrema { get; set; }
        public decimal TiempoMinimoDesmolde { get; set; }
        public decimal Agua { get; set; }
        public bool Activo { get; set; }
        public int IdUsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public decimal DensidadEsperadaMax { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<MaterialColor> MaterialColor { get; set; }
        public virtual ICollection<MaterialInyectora> MaterialInyectora { get; set; }
        public virtual ICollection<MaterialMateriaPrima> MaterialMateriaPrima { get; set; }
        public virtual ICollection<ProductoMaterial> ProductoMaterial { get; set; }
    }
}
