//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialMateriaPrima
    {
        public int IdMaterialMateriaPrima { get; set; }
        public int IdMaterial { get; set; }
        public int IdMateriaPrima { get; set; }
        public decimal Cantidad { get; set; }
        public decimal RelacionTrabajo { get; set; }
        public decimal TemperaturaTanque { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual MateriaPrima MateriaPrima { get; set; }
    }
}
