//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medida
    {
        public Medida()
        {
            this.MoldeMedida = new HashSet<MoldeMedida>();
            this.PedidoProductoMedida = new HashSet<PedidoProductoMedida>();
            this.ProductoMedida = new HashSet<ProductoMedida>();
        }
    
        public int IdMedida { get; set; }
        public int IdTipoMedida { get; set; }
        public int Orden { get; set; }
        public string Medida1 { get; set; }
    
        public virtual TipoMedida TipoMedida { get; set; }
        public virtual ICollection<MoldeMedida> MoldeMedida { get; set; }
        public virtual ICollection<PedidoProductoMedida> PedidoProductoMedida { get; set; }
        public virtual ICollection<ProductoMedida> ProductoMedida { get; set; }
    }
}
