//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Molde
    {
        public Molde()
        {
            this.MoldeInyectora = new HashSet<MoldeInyectora>();
            this.MoldeMedida = new HashSet<MoldeMedida>();
            this.Producto = new HashSet<Producto>();
        }
    
        public int IdMolde { get; set; }
        public string Nombre { get; set; }
        public bool Activo { get; set; }
        public int IdCliente { get; set; }
        public int IdGenero { get; set; }
        public int IdUsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public int IdTipoMedida { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual TipoMedida TipoMedida { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<MoldeInyectora> MoldeInyectora { get; set; }
        public virtual ICollection<MoldeMedida> MoldeMedida { get; set; }
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
