//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mueble
    {
        public int IdMueble { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Largo { get; set; }
        public Nullable<decimal> Ancho { get; set; }
        public bool PoseeRadio { get; set; }
        public Nullable<decimal> RadioMayor { get; set; }
        public Nullable<decimal> RadioMenor { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> IdUsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public decimal DistanciaProximoMueble { get; set; }
        public bool Activo { get; set; }
        public string Codigo { get; set; }
        public string Imagen { get; set; }
        public decimal DistanciaParedes { get; set; }
        public Nullable<int> OrdenDePrioridad { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
