//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mueble
    {
        public int IdMueble { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Largo { get; set; }
        public Nullable<decimal> Ancho { get; set; }
        public bool PoseeRadio { get; set; }
        public Nullable<decimal> RadioMayor { get; set; }
        public Nullable<decimal> RadioMenor { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> IdUsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public decimal DistanciaProximoMueble { get; set; }
        public bool Activo { get; set; }
        public string Codigo { get; set; }
        public string Imagen { get; set; }
        public decimal DistanciaParedes { get; set; }
        public Nullable<int> OrdenDePrioridad { get; set; }
        public string ImagenMueble { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
