//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoEstadoProceso
    {
        public int IdPedidoEstadoProceso { get; set; }
        public int IdPedidoEstado { get; set; }
        public int IdProceso { get; set; }
    
        public virtual PedidoEstado PedidoEstado { get; set; }
        public virtual Proceso Proceso { get; set; }
    }
}
