//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoProductoProceso
    {
        public PedidoProductoProceso()
        {
            this.PedidoProductoCajon = new HashSet<PedidoProductoCajon>();
        }
    
        public int IdPedidoProductoProceso { get; set; }
        public int IdProceso { get; set; }
        public Nullable<int> IdProgramacionPedidoProducto { get; set; }
        public int Cantidad { get; set; }
        public Nullable<decimal> Scrap { get; set; }
        public Nullable<int> IdPedidoProductoMedida { get; set; }
    
        public virtual ICollection<PedidoProductoCajon> PedidoProductoCajon { get; set; }
        public virtual PedidoProductoMedida PedidoProductoMedida { get; set; }
        public virtual Proceso Proceso { get; set; }
        public virtual ProgramacionPedidoProducto ProgramacionPedidoProducto { get; set; }
    }
}
