//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public Pedido()
        {
            this.PedidoProductoMedida = new HashSet<PedidoProductoMedida>();
        }
    
        public int IdPedido { get; set; }
        public int Numero { get; set; }
        public int IdPedidoEstado { get; set; }
        public int IdCliente { get; set; }
        public int IdClienteDireccionEntrega { get; set; }
        public int IdProducto { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public string OrdenCompra { get; set; }
        public int IdPedidoTipo { get; set; }
        public int IdUsuarioAlta { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ClienteDireccionEntrega ClienteDireccionEntrega { get; set; }
        public virtual PedidoEstado PedidoEstado { get; set; }
        public virtual PedidoTipo PedidoTipo { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<PedidoProductoMedida> PedidoProductoMedida { get; set; }
    }
}
