//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoProductoMedida
    {
        public PedidoProductoMedida()
        {
            this.EmbalajeBulto = new HashSet<EmbalajeBulto>();
            this.InyeccionEstacionPedido = new HashSet<InyeccionEstacionPedido>();
            this.PedidoProductoMedidaEstado = new HashSet<PedidoProductoMedidaEstado>();
            this.PedidoProductoProceso = new HashSet<PedidoProductoProceso>();
            this.ProgramacionDevolucion = new HashSet<ProgramacionDevolucion>();
            this.ProgramacionPedidoProducto = new HashSet<ProgramacionPedidoProducto>();
            this.Reinyeccion = new HashSet<Reinyeccion>();
        }
    
        public int IdPedidoProductoMedida { get; set; }
        public int IdPedido { get; set; }
        public int IdMedida { get; set; }
        public int Cantidad { get; set; }
        public Nullable<int> CantidadDespachada { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public decimal ScrapTotal { get; set; }
    
        public virtual ICollection<EmbalajeBulto> EmbalajeBulto { get; set; }
        public virtual ICollection<InyeccionEstacionPedido> InyeccionEstacionPedido { get; set; }
        public virtual Medida Medida { get; set; }
        public virtual Pedido Pedido { get; set; }
        public virtual ICollection<PedidoProductoMedidaEstado> PedidoProductoMedidaEstado { get; set; }
        public virtual ICollection<PedidoProductoProceso> PedidoProductoProceso { get; set; }
        public virtual ICollection<ProgramacionDevolucion> ProgramacionDevolucion { get; set; }
        public virtual ICollection<ProgramacionPedidoProducto> ProgramacionPedidoProducto { get; set; }
        public virtual ICollection<Reinyeccion> Reinyeccion { get; set; }
    }
}
