//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proceso
    {
        public Proceso()
        {
            this.DespachoTercero = new HashSet<DespachoTercero>();
            this.Embalaje = new HashSet<Embalaje>();
            this.PedidoEstadoProceso = new HashSet<PedidoEstadoProceso>();
            this.PedidoProductoProceso = new HashSet<PedidoProductoProceso>();
            this.ProductoProceso = new HashSet<ProductoProceso>();
            this.ProgramacionDevolucion = new HashSet<ProgramacionDevolucion>();
            this.ProveedorProceso = new HashSet<ProveedorProceso>();
            this.Reinyeccion = new HashSet<Reinyeccion>();
        }
    
        public int IdProceso { get; set; }
        public string Nombre { get; set; }
        public bool Terceriza { get; set; }
        public int IdUsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public bool Editable { get; set; }
        public int Orden { get; set; }
        public bool Visible { get; set; }
    
        public virtual ICollection<DespachoTercero> DespachoTercero { get; set; }
        public virtual ICollection<Embalaje> Embalaje { get; set; }
        public virtual ICollection<PedidoEstadoProceso> PedidoEstadoProceso { get; set; }
        public virtual ICollection<PedidoProductoProceso> PedidoProductoProceso { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<ProductoProceso> ProductoProceso { get; set; }
        public virtual ICollection<ProgramacionDevolucion> ProgramacionDevolucion { get; set; }
        public virtual ICollection<ProveedorProceso> ProveedorProceso { get; set; }
        public virtual ICollection<Reinyeccion> Reinyeccion { get; set; }
    }
}
