//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoMaterial
    {
        public int IdProductoMaterial { get; set; }
        public int IdProducto { get; set; }
        public int IdMaterial { get; set; }
        public int IdColor { get; set; }
        public Nullable<decimal> Peso { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Material Material { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
