//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoMedida
    {
        public int IdProductoMedida { get; set; }
        public int IdProducto { get; set; }
        public int IdMedida { get; set; }
        public int CantidadCanasto { get; set; }
    
        public virtual Medida Medida { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
