//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Pedido = new HashSet<Pedido>();
            this.ProductoInserto = new HashSet<ProductoInserto>();
            this.ProductoMaterial = new HashSet<ProductoMaterial>();
            this.ProductoMedida = new HashSet<ProductoMedida>();
            this.ProductoProceso = new HashSet<ProductoProceso>();
        }
    
        public int IdProducto { get; set; }
        public int IdCliente { get; set; }
        public string Nombre { get; set; }
        public string NombreCliente { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int IdGenero { get; set; }
        public int IdTipoMedida { get; set; }
        public int IdMolde { get; set; }
        public Nullable<int> IdLaca { get; set; }
        public bool PinturaTercerizada { get; set; }
        public string Comentario { get; set; }
        public bool Activo { get; set; }
        public Nullable<decimal> TiempoOtros { get; set; }
        public int IdProductoTipo { get; set; }
        public byte[] Imagen { get; set; }
        public decimal Scrap { get; set; }
        public int IdUsuarioAlta { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public int IdColor { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual Laca Laca { get; set; }
        public virtual Molde Molde { get; set; }
        public virtual ICollection<Pedido> Pedido { get; set; }
        public virtual ProductoTipo ProductoTipo { get; set; }
        public virtual TipoMedida TipoMedida { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<ProductoInserto> ProductoInserto { get; set; }
        public virtual ICollection<ProductoMaterial> ProductoMaterial { get; set; }
        public virtual ICollection<ProductoMedida> ProductoMedida { get; set; }
        public virtual ICollection<ProductoProceso> ProductoProceso { get; set; }
    }
}
