//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramacionPedidoProducto
    {
        public ProgramacionPedidoProducto()
        {
            this.InyeccionEstacionPedido = new HashSet<InyeccionEstacionPedido>();
            this.PedidoProductoProceso = new HashSet<PedidoProductoProceso>();
        }
    
        public int IdProgramacionPedidoProducto { get; set; }
        public int IdPedidoProductoMedida { get; set; }
        public int IdInyectoraEstacion { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime FechaMinimaInicio { get; set; }
        public System.DateTime HoraInicio { get; set; }
        public Nullable<System.DateTime> FechaProgramadaFin { get; set; }
        public Nullable<System.DateTime> HoraProgramadaFin { get; set; }
        public bool CambioMolde { get; set; }
        public Nullable<int> HorasProgramadas { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<int> IdReprogramacion { get; set; }
        public bool Reinyeccion { get; set; }
    
        public virtual ICollection<InyeccionEstacionPedido> InyeccionEstacionPedido { get; set; }
        public virtual InyectoraEstacion InyectoraEstacion { get; set; }
        public virtual PedidoProductoMedida PedidoProductoMedida { get; set; }
        public virtual ICollection<PedidoProductoProceso> PedidoProductoProceso { get; set; }
        public virtual Reprogramacion Reprogramacion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
