//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntoVenta
    {
        public PuntoVenta()
        {
            this.EmpresaCai = new HashSet<EmpresaCai>();
        }
    
        public int IdPuntoVenta { get; set; }
        public int Numero { get; set; }
        public int IdEmpresa { get; set; }
        public bool Activo { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<EmpresaCai> EmpresaCai { get; set; }
    }
}
