//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regla
    {
        public Regla()
        {
            this.RolRegla = new HashSet<RolRegla>();
        }
    
        public int IdRegla { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdModulo { get; set; }
    
        public virtual Modulo Modulo { get; set; }
        public virtual ICollection<RolRegla> RolRegla { get; set; }
    }
}
