//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regla
    {
        public Regla()
        {
            this.RolRegla = new HashSet<RolRegla>();
        }
    
        public int IdRegla { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdModulo { get; set; }
    
        public virtual Modulo Modulo { get; set; }
        public virtual ICollection<RolRegla> RolRegla { get; set; }
    }
}
