//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reprogramacion
    {
        public Reprogramacion()
        {
            this.HistoricoProgramacionPedidoProducto = new HashSet<HistoricoProgramacionPedidoProducto>();
            this.ProgramacionPedidoProducto = new HashSet<ProgramacionPedidoProducto>();
        }
    
        public int IdReprogramacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual ICollection<HistoricoProgramacionPedidoProducto> HistoricoProgramacionPedidoProducto { get; set; }
        public virtual ICollection<ProgramacionPedidoProducto> ProgramacionPedidoProducto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
