//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolRegla
    {
        public int IdRolRegla { get; set; }
        public int IdRegla { get; set; }
        public int IdRol { get; set; }
    
        public virtual Regla Regla { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
