//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolRegla
    {
        public int IdRolRegla { get; set; }
        public int IdRegla { get; set; }
        public int IdRol { get; set; }
    
        public virtual Regla Regla { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
