//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Cliente = new HashSet<Cliente>();
            this.Cliente1 = new HashSet<Cliente>();
            this.Localidad = new HashSet<Localidad>();
            this.Localidad1 = new HashSet<Localidad>();
            this.Mueble = new HashSet<Mueble>();
            this.Mueble1 = new HashSet<Mueble>();
            this.Pais = new HashSet<Pais>();
            this.Pais1 = new HashSet<Pais>();
            this.Provincia = new HashSet<Provincia>();
            this.Provincia1 = new HashSet<Provincia>();
            this.Rol = new HashSet<Rol>();
            this.Rol1 = new HashSet<Rol>();
            this.Usuario1 = new HashSet<Usuario>();
            this.Usuario11 = new HashSet<Usuario>();
        }
    
        public int IdUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public bool Activo { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public Nullable<int> IdRol { get; set; }
        public string ResetPasswordGuid { get; set; }
        public Nullable<System.DateTime> ResetPasswordFecha { get; set; }
        public int IdUsuarioAlta { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public bool Interno { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual ICollection<Cliente> Cliente1 { get; set; }
        public virtual ICollection<Localidad> Localidad { get; set; }
        public virtual ICollection<Localidad> Localidad1 { get; set; }
        public virtual ICollection<Mueble> Mueble { get; set; }
        public virtual ICollection<Mueble> Mueble1 { get; set; }
        public virtual ICollection<Pais> Pais { get; set; }
        public virtual ICollection<Pais> Pais1 { get; set; }
        public virtual ICollection<Provincia> Provincia { get; set; }
        public virtual ICollection<Provincia> Provincia1 { get; set; }
        public virtual ICollection<Rol> Rol { get; set; }
        public virtual ICollection<Rol> Rol1 { get; set; }
        public virtual Rol Rol2 { get; set; }
        public virtual ICollection<Usuario> Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual ICollection<Usuario> Usuario11 { get; set; }
        public virtual Usuario Usuario3 { get; set; }
    }
}
