//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngematicaAngularBase.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Cliente = new HashSet<Cliente>();
            this.Cliente1 = new HashSet<Cliente>();
            this.Color = new HashSet<Color>();
            this.Color1 = new HashSet<Color>();
            this.HistoricoProgramacionPedidoProducto = new HashSet<HistoricoProgramacionPedidoProducto>();
            this.Inserto = new HashSet<Inserto>();
            this.Inserto1 = new HashSet<Inserto>();
            this.Inyectora = new HashSet<Inyectora>();
            this.Inyectora1 = new HashSet<Inyectora>();
            this.Laca = new HashSet<Laca>();
            this.Laca1 = new HashSet<Laca>();
            this.Localidad = new HashSet<Localidad>();
            this.Localidad1 = new HashSet<Localidad>();
            this.Material = new HashSet<Material>();
            this.Material1 = new HashSet<Material>();
            this.MateriaPrima = new HashSet<MateriaPrima>();
            this.MateriaPrima1 = new HashSet<MateriaPrima>();
            this.MateriaPrimaMarca = new HashSet<MateriaPrimaMarca>();
            this.MateriaPrimaMarca1 = new HashSet<MateriaPrimaMarca>();
            this.Molde = new HashSet<Molde>();
            this.Molde1 = new HashSet<Molde>();
            this.Pais = new HashSet<Pais>();
            this.Pais1 = new HashSet<Pais>();
            this.Pedido = new HashSet<Pedido>();
            this.Pedido1 = new HashSet<Pedido>();
            this.Proceso = new HashSet<Proceso>();
            this.Proceso1 = new HashSet<Proceso>();
            this.Producto = new HashSet<Producto>();
            this.Producto1 = new HashSet<Producto>();
            this.ProgramacionPedidoProducto = new HashSet<ProgramacionPedidoProducto>();
            this.Proveedor = new HashSet<Proveedor>();
            this.Proveedor1 = new HashSet<Proveedor>();
            this.Provincia = new HashSet<Provincia>();
            this.Provincia1 = new HashSet<Provincia>();
            this.Reprogramacion = new HashSet<Reprogramacion>();
            this.Rol = new HashSet<Rol>();
            this.Rol1 = new HashSet<Rol>();
            this.TipoMedida = new HashSet<TipoMedida>();
            this.TipoMedida1 = new HashSet<TipoMedida>();
            this.Usuario1 = new HashSet<Usuario>();
            this.Usuario11 = new HashSet<Usuario>();
        }
    
        public int IdUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public bool Activo { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public Nullable<int> IdRol { get; set; }
        public string ResetPasswordGuid { get; set; }
        public Nullable<System.DateTime> ResetPasswordFecha { get; set; }
        public int IdUsuarioAlta { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public bool Interno { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual ICollection<Cliente> Cliente1 { get; set; }
        public virtual ICollection<Color> Color { get; set; }
        public virtual ICollection<Color> Color1 { get; set; }
        public virtual ICollection<HistoricoProgramacionPedidoProducto> HistoricoProgramacionPedidoProducto { get; set; }
        public virtual ICollection<Inserto> Inserto { get; set; }
        public virtual ICollection<Inserto> Inserto1 { get; set; }
        public virtual ICollection<Inyectora> Inyectora { get; set; }
        public virtual ICollection<Inyectora> Inyectora1 { get; set; }
        public virtual ICollection<Laca> Laca { get; set; }
        public virtual ICollection<Laca> Laca1 { get; set; }
        public virtual ICollection<Localidad> Localidad { get; set; }
        public virtual ICollection<Localidad> Localidad1 { get; set; }
        public virtual ICollection<Material> Material { get; set; }
        public virtual ICollection<Material> Material1 { get; set; }
        public virtual ICollection<MateriaPrima> MateriaPrima { get; set; }
        public virtual ICollection<MateriaPrima> MateriaPrima1 { get; set; }
        public virtual ICollection<MateriaPrimaMarca> MateriaPrimaMarca { get; set; }
        public virtual ICollection<MateriaPrimaMarca> MateriaPrimaMarca1 { get; set; }
        public virtual ICollection<Molde> Molde { get; set; }
        public virtual ICollection<Molde> Molde1 { get; set; }
        public virtual ICollection<Pais> Pais { get; set; }
        public virtual ICollection<Pais> Pais1 { get; set; }
        public virtual ICollection<Pedido> Pedido { get; set; }
        public virtual ICollection<Pedido> Pedido1 { get; set; }
        public virtual ICollection<Proceso> Proceso { get; set; }
        public virtual ICollection<Proceso> Proceso1 { get; set; }
        public virtual ICollection<Producto> Producto { get; set; }
        public virtual ICollection<Producto> Producto1 { get; set; }
        public virtual ICollection<ProgramacionPedidoProducto> ProgramacionPedidoProducto { get; set; }
        public virtual ICollection<Proveedor> Proveedor { get; set; }
        public virtual ICollection<Proveedor> Proveedor1 { get; set; }
        public virtual ICollection<Provincia> Provincia { get; set; }
        public virtual ICollection<Provincia> Provincia1 { get; set; }
        public virtual ICollection<Reprogramacion> Reprogramacion { get; set; }
        public virtual ICollection<Rol> Rol { get; set; }
        public virtual ICollection<Rol> Rol1 { get; set; }
        public virtual Rol Rol2 { get; set; }
        public virtual ICollection<TipoMedida> TipoMedida { get; set; }
        public virtual ICollection<TipoMedida> TipoMedida1 { get; set; }
        public virtual ICollection<Usuario> Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual ICollection<Usuario> Usuario11 { get; set; }
        public virtual Usuario Usuario3 { get; set; }
    }
}
