//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class ClienteSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithIdCliente(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdCliente == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithRazonSocial(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, string value)
		{
			if (value != null)
				return source.Where(p => p.RazonSocial == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithContainsRazonSocial(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, string value)
		{
			if (value != null)
				return source.Where(p => p.RazonSocial.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithEmail(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Email == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithContainsEmail(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Email.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithTelefono(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Telefono == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithContainsTelefono(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Telefono.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithNombreContacto(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, string value)
		{
			if (value != null)
				return source.Where(p => p.NombreContacto == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithContainsNombreContacto(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, string value)
		{
			if (value != null)
				return source.Where(p => p.NombreContacto.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithCUIT(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, string value)
		{
			if (value != null)
				return source.Where(p => p.CUIT == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithContainsCUIT(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, string value)
		{
			if (value != null)
				return source.Where(p => p.CUIT.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithIdLocalidad(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdLocalidad == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithDireccion(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Direccion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithContainsDireccion(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Direccion.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithActivo(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, bool? value)
		{
			if (value != null)
				return source.Where(p => p.Activo == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithIdUsuarioAlta(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdUsuarioAlta == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithFechaAlta(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.FechaAlta == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithFechaAltaBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaAlta >= lower);

            if (upper != null)
                range = range.Where(p => p.FechaAlta <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithFechaAltaBetween(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaAlta >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.FechaAlta < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithIdUsuarioModificacion(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdUsuarioModificacion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithFechaModificacion(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.FechaModificacion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithFechaModificacionBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaModificacion >= lower);

            if (upper != null)
                range = range.Where(p => p.FechaModificacion <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithFechaModificacionBetween(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaModificacion >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.FechaModificacion < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithCodigoPostal(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, string value)
		{
			if (value != null)
				return source.Where(p => p.CodigoPostal == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithContainsCodigoPostal(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, string value)
		{
			if (value != null)
				return source.Where(p => p.CodigoPostal.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Cliente> WithCodigoCliente(this IQueryable<IngematicaAngularBase.Model.Entities.Cliente> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.CodigoCliente == value);
			
			return source;
		}
	}
}
