//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class ClienteDireccionEntregaSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.ClienteDireccionEntrega> WithIdClienteDireccionEntrega(this IQueryable<IngematicaAngularBase.Model.Entities.ClienteDireccionEntrega> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdClienteDireccionEntrega == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.ClienteDireccionEntrega> WithNombre(this IQueryable<IngematicaAngularBase.Model.Entities.ClienteDireccionEntrega> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Nombre == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.ClienteDireccionEntrega> WithContainsNombre(this IQueryable<IngematicaAngularBase.Model.Entities.ClienteDireccionEntrega> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Nombre.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.ClienteDireccionEntrega> WithIdCliente(this IQueryable<IngematicaAngularBase.Model.Entities.ClienteDireccionEntrega> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdCliente == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.ClienteDireccionEntrega> WithIdLocalidad(this IQueryable<IngematicaAngularBase.Model.Entities.ClienteDireccionEntrega> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdLocalidad == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.ClienteDireccionEntrega> WithDireccion(this IQueryable<IngematicaAngularBase.Model.Entities.ClienteDireccionEntrega> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Direccion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.ClienteDireccionEntrega> WithContainsDireccion(this IQueryable<IngematicaAngularBase.Model.Entities.ClienteDireccionEntrega> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Direccion.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.ClienteDireccionEntrega> WithCodigoPostal(this IQueryable<IngematicaAngularBase.Model.Entities.ClienteDireccionEntrega> source, string value)
		{
			if (value != null)
				return source.Where(p => p.CodigoPostal == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.ClienteDireccionEntrega> WithContainsCodigoPostal(this IQueryable<IngematicaAngularBase.Model.Entities.ClienteDireccionEntrega> source, string value)
		{
			if (value != null)
				return source.Where(p => p.CodigoPostal.Contains(value));
			
			return source;
		}

	}
}
