//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class ColaImpresionSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.ColaImpresion> WithIdColaImpresion(this IQueryable<IngematicaAngularBase.Model.Entities.ColaImpresion> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdColaImpresion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.ColaImpresion> WithEntidad(this IQueryable<IngematicaAngularBase.Model.Entities.ColaImpresion> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Entidad == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.ColaImpresion> WithContainsEntidad(this IQueryable<IngematicaAngularBase.Model.Entities.ColaImpresion> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Entidad.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.ColaImpresion> WithData(this IQueryable<IngematicaAngularBase.Model.Entities.ColaImpresion> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Data == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.ColaImpresion> WithContainsData(this IQueryable<IngematicaAngularBase.Model.Entities.ColaImpresion> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Data.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.ColaImpresion> WithImpreso(this IQueryable<IngematicaAngularBase.Model.Entities.ColaImpresion> source, bool? value)
		{
			if (value != null)
				return source.Where(p => p.Impreso == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.ColaImpresion> WithPath(this IQueryable<IngematicaAngularBase.Model.Entities.ColaImpresion> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Path == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.ColaImpresion> WithContainsPath(this IQueryable<IngematicaAngularBase.Model.Entities.ColaImpresion> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Path.Contains(value));
			
			return source;
		}

	}
}
