//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class DespachoTerceroBultoEstadoSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoEstado> WithIdDespachoTerceroBultoEstado(this IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoEstado> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdDespachoTerceroBultoEstado == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoEstado> WithNombre(this IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoEstado> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Nombre == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoEstado> WithContainsNombre(this IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoEstado> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Nombre.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoEstado> WithCodigo(this IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoEstado> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Codigo == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoEstado> WithContainsCodigo(this IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoEstado> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Codigo.Contains(value));
			
			return source;
		}

	}
}
