//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class DespachoTerceroBultoRespuestaSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoRespuesta> WithIdDespachoTerceroBultoRespuesta(this IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoRespuesta> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdDespachoTerceroBultoRespuesta == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoRespuesta> WithIdDespachoTerceroRespuesta(this IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoRespuesta> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdDespachoTerceroRespuesta == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoRespuesta> WithIdEmbalaje(this IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoRespuesta> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdEmbalaje == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoRespuesta> WithIdEmbalajeRespuesta(this IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoRespuesta> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdEmbalajeRespuesta == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoRespuesta> WithCantidadIngreso(this IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoRespuesta> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.CantidadIngreso == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoRespuesta> WithScrap(this IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoRespuesta> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.Scrap == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoRespuesta> WithIdPedidoProductoMedida(this IQueryable<IngematicaAngularBase.Model.Entities.DespachoTerceroBultoRespuesta> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdPedidoProductoMedida == value);
			
			return source;
		}
	}
}
