//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class DespachoTerceroSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.DespachoTercero> WithIdDespachoTercero(this IQueryable<IngematicaAngularBase.Model.Entities.DespachoTercero> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdDespachoTercero == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.DespachoTercero> WithIdProceso(this IQueryable<IngematicaAngularBase.Model.Entities.DespachoTercero> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdProceso == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.DespachoTercero> WithNumero(this IQueryable<IngematicaAngularBase.Model.Entities.DespachoTercero> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.Numero == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.DespachoTercero> WithFecha(this IQueryable<IngematicaAngularBase.Model.Entities.DespachoTercero> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.Fecha == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.DespachoTercero> WithFechaBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.DespachoTercero> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.Fecha >= lower);

            if (upper != null)
                range = range.Where(p => p.Fecha <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.DespachoTercero> WithFechaBetween(this IQueryable<IngematicaAngularBase.Model.Entities.DespachoTercero> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.Fecha >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.Fecha < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.DespachoTercero> WithIdProveedor(this IQueryable<IngematicaAngularBase.Model.Entities.DespachoTercero> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdProveedor == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.DespachoTercero> WithCantidadEgreso(this IQueryable<IngematicaAngularBase.Model.Entities.DespachoTercero> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.CantidadEgreso == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.DespachoTercero> WithCantidadIngreso(this IQueryable<IngematicaAngularBase.Model.Entities.DespachoTercero> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.CantidadIngreso == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.DespachoTercero> WithScrapTotal(this IQueryable<IngematicaAngularBase.Model.Entities.DespachoTercero> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.ScrapTotal == value);
			
			return source;
		}
	}
}
