//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class EmbalajeSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.Embalaje> WithIdEmbalaje(this IQueryable<IngematicaAngularBase.Model.Entities.Embalaje> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdEmbalaje == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Embalaje> WithIdProceso(this IQueryable<IngematicaAngularBase.Model.Entities.Embalaje> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdProceso == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Embalaje> WithNumero(this IQueryable<IngematicaAngularBase.Model.Entities.Embalaje> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.Numero == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Embalaje> WithFecha(this IQueryable<IngematicaAngularBase.Model.Entities.Embalaje> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.Fecha == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Embalaje> WithFechaBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.Embalaje> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.Fecha >= lower);

            if (upper != null)
                range = range.Where(p => p.Fecha <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Embalaje> WithFechaBetween(this IQueryable<IngematicaAngularBase.Model.Entities.Embalaje> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.Fecha >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.Fecha < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Embalaje> WithIdCliente(this IQueryable<IngematicaAngularBase.Model.Entities.Embalaje> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdCliente == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Embalaje> WithIdPedido(this IQueryable<IngematicaAngularBase.Model.Entities.Embalaje> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdPedido == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Embalaje> WithCantidad(this IQueryable<IngematicaAngularBase.Model.Entities.Embalaje> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.Cantidad == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Embalaje> WithDespachado(this IQueryable<IngematicaAngularBase.Model.Entities.Embalaje> source, bool? value)
		{
			if (value != null)
				return source.Where(p => p.Despachado == value);
			
			return source;
		}
	}
}
