//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class EmpresaCaiSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.EmpresaCai> WithIdEmpresaCai(this IQueryable<IngematicaAngularBase.Model.Entities.EmpresaCai> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdEmpresaCai == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.EmpresaCai> WithIdEmpresa(this IQueryable<IngematicaAngularBase.Model.Entities.EmpresaCai> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdEmpresa == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.EmpresaCai> WithIdPuntoVenta(this IQueryable<IngematicaAngularBase.Model.Entities.EmpresaCai> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdPuntoVenta == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.EmpresaCai> WithNumero(this IQueryable<IngematicaAngularBase.Model.Entities.EmpresaCai> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Numero == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.EmpresaCai> WithContainsNumero(this IQueryable<IngematicaAngularBase.Model.Entities.EmpresaCai> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Numero.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.EmpresaCai> WithFechaVencimiento(this IQueryable<IngematicaAngularBase.Model.Entities.EmpresaCai> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.FechaVencimiento == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.EmpresaCai> WithFechaVencimientoBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.EmpresaCai> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaVencimiento >= lower);

            if (upper != null)
                range = range.Where(p => p.FechaVencimiento <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.EmpresaCai> WithFechaVencimientoBetween(this IQueryable<IngematicaAngularBase.Model.Entities.EmpresaCai> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaVencimiento >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.FechaVencimiento < upper);
			}

            return range;
		}

	}
}
