//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class InyeccionEstacionPedidoSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacionPedido> WithIdInyeccionEstacionPedido(this IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacionPedido> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdInyeccionEstacionPedido == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacionPedido> WithIdInyeccionEstacion(this IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacionPedido> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdInyeccionEstacion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacionPedido> WithIdProgramacionPedidoProducto(this IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacionPedido> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdProgramacionPedidoProducto == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacionPedido> WithIdPedidoProductoMedida(this IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacionPedido> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdPedidoProductoMedida == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacionPedido> WithScrap(this IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacionPedido> source, decimal? value)
		{
			if (value != null)
				return source.Where(p => p.Scrap == value);
			
			return source;
		}
	}
}
