//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class InyeccionSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.Inyeccion> WithIdInyeccion(this IQueryable<IngematicaAngularBase.Model.Entities.Inyeccion> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdInyeccion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Inyeccion> WithFecha(this IQueryable<IngematicaAngularBase.Model.Entities.Inyeccion> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.Fecha == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Inyeccion> WithFechaBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.Inyeccion> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.Fecha >= lower);

            if (upper != null)
                range = range.Where(p => p.Fecha <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Inyeccion> WithFechaBetween(this IQueryable<IngematicaAngularBase.Model.Entities.Inyeccion> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.Fecha >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.Fecha < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Inyeccion> WithNumero(this IQueryable<IngematicaAngularBase.Model.Entities.Inyeccion> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.Numero == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Inyeccion> WithIdInyectora(this IQueryable<IngematicaAngularBase.Model.Entities.Inyeccion> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdInyectora == value);
			
			return source;
		}
	}
}
