//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class InyectoraEstacionSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.InyectoraEstacion> WithIdInyectoraEstacion(this IQueryable<IngematicaAngularBase.Model.Entities.InyectoraEstacion> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdInyectoraEstacion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.InyectoraEstacion> WithIdInyectora(this IQueryable<IngematicaAngularBase.Model.Entities.InyectoraEstacion> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdInyectora == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.InyectoraEstacion> WithNumero(this IQueryable<IngematicaAngularBase.Model.Entities.InyectoraEstacion> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.Numero == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.InyectoraEstacion> WithActivo(this IQueryable<IngematicaAngularBase.Model.Entities.InyectoraEstacion> source, bool? value)
		{
			if (value != null)
				return source.Where(p => p.Activo == value);
			
			return source;
		}
	}
}
