//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class InyeccionEstacionCajonSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacionCajon> WithInyeccionEstacionCajon1(this IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacionCajon> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.InyeccionEstacionCajon1 == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacionCajon> WithCajon(this IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacionCajon> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.Cajon == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacionCajon> WithCantidad(this IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacionCajon> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.Cantidad == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacionCajon> WithIdInyeccionEstacionPedido(this IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacionCajon> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdInyeccionEstacionPedido == value);
			
			return source;
		}
	}
}
