//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class InyeccionEstacionSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacion> WithIdInyeccionEstacion(this IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacion> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdInyeccionEstacion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacion> WithIdInyeccion(this IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacion> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdInyeccion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacion> WithIdInyectoraEstacion(this IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacion> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdInyectoraEstacion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacion> WithCantidadTotal(this IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacion> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.CantidadTotal == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacion> WithScrapTotal(this IQueryable<IngematicaAngularBase.Model.Entities.InyeccionEstacion> source, decimal? value)
		{
			if (value != null)
				return source.Where(p => p.ScrapTotal == value);
			
			return source;
		}
	}
}
