//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class InyectoraOperarioSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.InyectoraOperario> WithIdInyectoraOperario(this IQueryable<IngematicaAngularBase.Model.Entities.InyectoraOperario> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdInyectoraOperario == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.InyectoraOperario> WithIdInyectora(this IQueryable<IngematicaAngularBase.Model.Entities.InyectoraOperario> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdInyectora == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.InyectoraOperario> WithPersonas(this IQueryable<IngematicaAngularBase.Model.Entities.InyectoraOperario> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.Personas == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.InyectoraOperario> WithHoras(this IQueryable<IngematicaAngularBase.Model.Entities.InyectoraOperario> source, decimal? value)
		{
			if (value != null)
				return source.Where(p => p.Horas == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.InyectoraOperario> WithFechaJornada(this IQueryable<IngematicaAngularBase.Model.Entities.InyectoraOperario> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.FechaJornada == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.InyectoraOperario> WithFechaJornadaBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.InyectoraOperario> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaJornada >= lower);

            if (upper != null)
                range = range.Where(p => p.FechaJornada <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.InyectoraOperario> WithFechaJornadaBetween(this IQueryable<IngematicaAngularBase.Model.Entities.InyectoraOperario> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaJornada >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.FechaJornada < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.InyectoraOperario> WithHoraInicioJornada(this IQueryable<IngematicaAngularBase.Model.Entities.InyectoraOperario> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.HoraInicioJornada == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.InyectoraOperario> WithHoraInicioJornadaBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.InyectoraOperario> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.HoraInicioJornada >= lower);

            if (upper != null)
                range = range.Where(p => p.HoraInicioJornada <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.InyectoraOperario> WithHoraInicioJornadaBetween(this IQueryable<IngematicaAngularBase.Model.Entities.InyectoraOperario> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.HoraInicioJornada >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.HoraInicioJornada < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.InyectoraOperario> WithCantidadSuelas(this IQueryable<IngematicaAngularBase.Model.Entities.InyectoraOperario> source, decimal? value)
		{
			if (value != null)
				return source.Where(p => p.CantidadSuelas == value);
			
			return source;
		}
	}
}
