//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class LacaSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.Laca> WithIdLaca(this IQueryable<IngematicaAngularBase.Model.Entities.Laca> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdLaca == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Laca> WithNombre(this IQueryable<IngematicaAngularBase.Model.Entities.Laca> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Nombre == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Laca> WithContainsNombre(this IQueryable<IngematicaAngularBase.Model.Entities.Laca> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Nombre.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Laca> WithColor(this IQueryable<IngematicaAngularBase.Model.Entities.Laca> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Color == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Laca> WithContainsColor(this IQueryable<IngematicaAngularBase.Model.Entities.Laca> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Color.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Laca> WithIdUsuarioAlta(this IQueryable<IngematicaAngularBase.Model.Entities.Laca> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdUsuarioAlta == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Laca> WithFechaAlta(this IQueryable<IngematicaAngularBase.Model.Entities.Laca> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.FechaAlta == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Laca> WithFechaAltaBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.Laca> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaAlta >= lower);

            if (upper != null)
                range = range.Where(p => p.FechaAlta <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Laca> WithFechaAltaBetween(this IQueryable<IngematicaAngularBase.Model.Entities.Laca> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaAlta >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.FechaAlta < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Laca> WithIdUsuarioModificacion(this IQueryable<IngematicaAngularBase.Model.Entities.Laca> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdUsuarioModificacion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Laca> WithFechaModificacion(this IQueryable<IngematicaAngularBase.Model.Entities.Laca> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.FechaModificacion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Laca> WithFechaModificacionBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.Laca> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaModificacion >= lower);

            if (upper != null)
                range = range.Where(p => p.FechaModificacion <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Laca> WithFechaModificacionBetween(this IQueryable<IngematicaAngularBase.Model.Entities.Laca> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaModificacion >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.FechaModificacion < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Laca> WithComentario(this IQueryable<IngematicaAngularBase.Model.Entities.Laca> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Comentario == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Laca> WithContainsComentario(this IQueryable<IngematicaAngularBase.Model.Entities.Laca> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Comentario.Contains(value));
			
			return source;
		}

	}
}
