//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class LocalidadSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.Localidad> WithIdLocalidad(this IQueryable<IngematicaAngularBase.Model.Entities.Localidad> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdLocalidad == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Localidad> WithIdProvincia(this IQueryable<IngematicaAngularBase.Model.Entities.Localidad> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdProvincia == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Localidad> WithNombre(this IQueryable<IngematicaAngularBase.Model.Entities.Localidad> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Nombre == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Localidad> WithContainsNombre(this IQueryable<IngematicaAngularBase.Model.Entities.Localidad> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Nombre.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Localidad> WithCodigoPostal(this IQueryable<IngematicaAngularBase.Model.Entities.Localidad> source, string value)
		{
			if (value != null)
				return source.Where(p => p.CodigoPostal == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Localidad> WithContainsCodigoPostal(this IQueryable<IngematicaAngularBase.Model.Entities.Localidad> source, string value)
		{
			if (value != null)
				return source.Where(p => p.CodigoPostal.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Localidad> WithIdUsuarioAlta(this IQueryable<IngematicaAngularBase.Model.Entities.Localidad> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdUsuarioAlta == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Localidad> WithFechaAlta(this IQueryable<IngematicaAngularBase.Model.Entities.Localidad> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.FechaAlta == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Localidad> WithFechaAltaBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.Localidad> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaAlta >= lower);

            if (upper != null)
                range = range.Where(p => p.FechaAlta <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Localidad> WithFechaAltaBetween(this IQueryable<IngematicaAngularBase.Model.Entities.Localidad> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaAlta >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.FechaAlta < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Localidad> WithIdUsuarioModificacion(this IQueryable<IngematicaAngularBase.Model.Entities.Localidad> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdUsuarioModificacion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Localidad> WithFechaModificacion(this IQueryable<IngematicaAngularBase.Model.Entities.Localidad> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.FechaModificacion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Localidad> WithFechaModificacionBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.Localidad> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaModificacion >= lower);

            if (upper != null)
                range = range.Where(p => p.FechaModificacion <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Localidad> WithFechaModificacionBetween(this IQueryable<IngematicaAngularBase.Model.Entities.Localidad> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaModificacion >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.FechaModificacion < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Localidad> WithActivo(this IQueryable<IngematicaAngularBase.Model.Entities.Localidad> source, bool? value)
		{
			if (value != null)
				return source.Where(p => p.Activo == value);
			
			return source;
		}
	}
}
