//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class LogSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.Log> WithIdLog(this IQueryable<IngematicaAngularBase.Model.Entities.Log> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdLog == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Log> WithFecha(this IQueryable<IngematicaAngularBase.Model.Entities.Log> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.Fecha == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Log> WithFechaBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.Log> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.Fecha >= lower);

            if (upper != null)
                range = range.Where(p => p.Fecha <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Log> WithFechaBetween(this IQueryable<IngematicaAngularBase.Model.Entities.Log> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.Fecha >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.Fecha < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Log> WithDescripcion(this IQueryable<IngematicaAngularBase.Model.Entities.Log> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Descripcion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Log> WithContainsDescripcion(this IQueryable<IngematicaAngularBase.Model.Entities.Log> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Descripcion.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Log> WithDescripcion2(this IQueryable<IngematicaAngularBase.Model.Entities.Log> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Descripcion2 == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Log> WithContainsDescripcion2(this IQueryable<IngematicaAngularBase.Model.Entities.Log> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Descripcion2.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Log> WithController(this IQueryable<IngematicaAngularBase.Model.Entities.Log> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Controller == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Log> WithContainsController(this IQueryable<IngematicaAngularBase.Model.Entities.Log> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Controller.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Log> WithAccion(this IQueryable<IngematicaAngularBase.Model.Entities.Log> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Accion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Log> WithContainsAccion(this IQueryable<IngematicaAngularBase.Model.Entities.Log> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Accion.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Log> WithOtrosDatos(this IQueryable<IngematicaAngularBase.Model.Entities.Log> source, string value)
		{
			if (value != null)
				return source.Where(p => p.OtrosDatos == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Log> WithContainsOtrosDatos(this IQueryable<IngematicaAngularBase.Model.Entities.Log> source, string value)
		{
			if (value != null)
				return source.Where(p => p.OtrosDatos.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Log> WithUsuario(this IQueryable<IngematicaAngularBase.Model.Entities.Log> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Usuario == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Log> WithContainsUsuario(this IQueryable<IngematicaAngularBase.Model.Entities.Log> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Usuario.Contains(value));
			
			return source;
		}

	}
}
