//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class MaterialSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.Material> WithIdMaterial(this IQueryable<IngematicaAngularBase.Model.Entities.Material> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdMaterial == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Material> WithNombre(this IQueryable<IngematicaAngularBase.Model.Entities.Material> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Nombre == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Material> WithContainsNombre(this IQueryable<IngematicaAngularBase.Model.Entities.Material> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Nombre.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Material> WithDensidadEsperadaMin(this IQueryable<IngematicaAngularBase.Model.Entities.Material> source, decimal? value)
		{
			if (value != null)
				return source.Where(p => p.DensidadEsperadaMin == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Material> WithTiempoCrema(this IQueryable<IngematicaAngularBase.Model.Entities.Material> source, decimal? value)
		{
			if (value != null)
				return source.Where(p => p.TiempoCrema == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Material> WithTiempoMinimoDesmolde(this IQueryable<IngematicaAngularBase.Model.Entities.Material> source, decimal? value)
		{
			if (value != null)
				return source.Where(p => p.TiempoMinimoDesmolde == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Material> WithAgua(this IQueryable<IngematicaAngularBase.Model.Entities.Material> source, decimal? value)
		{
			if (value != null)
				return source.Where(p => p.Agua == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Material> WithActivo(this IQueryable<IngematicaAngularBase.Model.Entities.Material> source, bool? value)
		{
			if (value != null)
				return source.Where(p => p.Activo == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Material> WithIdUsuarioAlta(this IQueryable<IngematicaAngularBase.Model.Entities.Material> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdUsuarioAlta == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Material> WithFechaAlta(this IQueryable<IngematicaAngularBase.Model.Entities.Material> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.FechaAlta == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Material> WithFechaAltaBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.Material> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaAlta >= lower);

            if (upper != null)
                range = range.Where(p => p.FechaAlta <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Material> WithFechaAltaBetween(this IQueryable<IngematicaAngularBase.Model.Entities.Material> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaAlta >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.FechaAlta < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Material> WithIdUsuarioModificacion(this IQueryable<IngematicaAngularBase.Model.Entities.Material> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdUsuarioModificacion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Material> WithFechaModificacion(this IQueryable<IngematicaAngularBase.Model.Entities.Material> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.FechaModificacion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Material> WithFechaModificacionBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.Material> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaModificacion >= lower);

            if (upper != null)
                range = range.Where(p => p.FechaModificacion <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Material> WithFechaModificacionBetween(this IQueryable<IngematicaAngularBase.Model.Entities.Material> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaModificacion >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.FechaModificacion < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Material> WithDensidadEsperadaMax(this IQueryable<IngematicaAngularBase.Model.Entities.Material> source, decimal? value)
		{
			if (value != null)
				return source.Where(p => p.DensidadEsperadaMax == value);
			
			return source;
		}
	}
}
