//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class MaterialTipoSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.MaterialTipo> WithIdMaterialTipo(this IQueryable<IngematicaAngularBase.Model.Entities.MaterialTipo> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdMaterialTipo == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.MaterialTipo> WithNombre(this IQueryable<IngematicaAngularBase.Model.Entities.MaterialTipo> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.Nombre == value);
			
			return source;
		}
	}
}
