//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class MaterialMateriaPrimaSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.MaterialMateriaPrima> WithIdMaterialMateriaPrima(this IQueryable<IngematicaAngularBase.Model.Entities.MaterialMateriaPrima> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdMaterialMateriaPrima == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.MaterialMateriaPrima> WithIdMaterial(this IQueryable<IngematicaAngularBase.Model.Entities.MaterialMateriaPrima> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdMaterial == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.MaterialMateriaPrima> WithIdMateriaPrima(this IQueryable<IngematicaAngularBase.Model.Entities.MaterialMateriaPrima> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdMateriaPrima == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.MaterialMateriaPrima> WithCantidad(this IQueryable<IngematicaAngularBase.Model.Entities.MaterialMateriaPrima> source, decimal? value)
		{
			if (value != null)
				return source.Where(p => p.Cantidad == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.MaterialMateriaPrima> WithRelacionTrabajo(this IQueryable<IngematicaAngularBase.Model.Entities.MaterialMateriaPrima> source, decimal? value)
		{
			if (value != null)
				return source.Where(p => p.RelacionTrabajo == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.MaterialMateriaPrima> WithTemperaturaTanque(this IQueryable<IngematicaAngularBase.Model.Entities.MaterialMateriaPrima> source, decimal? value)
		{
			if (value != null)
				return source.Where(p => p.TemperaturaTanque == value);
			
			return source;
		}
	}
}
