//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class MaterialColorSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.MaterialColor> WithIdMaterialColor(this IQueryable<IngematicaAngularBase.Model.Entities.MaterialColor> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdMaterialColor == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.MaterialColor> WithIdMaterial(this IQueryable<IngematicaAngularBase.Model.Entities.MaterialColor> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdMaterial == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.MaterialColor> WithIdColor(this IQueryable<IngematicaAngularBase.Model.Entities.MaterialColor> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdColor == value);
			
			return source;
		}
	}
}
