//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class MedidaSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.Medida> WithIdMedida(this IQueryable<IngematicaAngularBase.Model.Entities.Medida> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdMedida == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Medida> WithIdTipoMedida(this IQueryable<IngematicaAngularBase.Model.Entities.Medida> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdTipoMedida == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Medida> WithOrden(this IQueryable<IngematicaAngularBase.Model.Entities.Medida> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.Orden == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Medida> WithMedida1(this IQueryable<IngematicaAngularBase.Model.Entities.Medida> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Medida1 == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Medida> WithContainsMedida1(this IQueryable<IngematicaAngularBase.Model.Entities.Medida> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Medida1.Contains(value));
			
			return source;
		}

	}
}
