//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class ModuloSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.Modulo> WithIdModulo(this IQueryable<IngematicaAngularBase.Model.Entities.Modulo> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdModulo == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Modulo> WithNombre(this IQueryable<IngematicaAngularBase.Model.Entities.Modulo> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Nombre == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Modulo> WithContainsNombre(this IQueryable<IngematicaAngularBase.Model.Entities.Modulo> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Nombre.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Modulo> WithActivo(this IQueryable<IngematicaAngularBase.Model.Entities.Modulo> source, bool? value)
		{
			if (value != null)
				return source.Where(p => p.Activo == value);
			
			return source;
		}
	}
}
