//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class MoldeSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.Molde> WithIdMolde(this IQueryable<IngematicaAngularBase.Model.Entities.Molde> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdMolde == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Molde> WithNombre(this IQueryable<IngematicaAngularBase.Model.Entities.Molde> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Nombre == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Molde> WithContainsNombre(this IQueryable<IngematicaAngularBase.Model.Entities.Molde> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Nombre.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Molde> WithActivo(this IQueryable<IngematicaAngularBase.Model.Entities.Molde> source, bool? value)
		{
			if (value != null)
				return source.Where(p => p.Activo == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Molde> WithIdCliente(this IQueryable<IngematicaAngularBase.Model.Entities.Molde> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdCliente == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Molde> WithIdGenero(this IQueryable<IngematicaAngularBase.Model.Entities.Molde> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdGenero == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Molde> WithIdUsuarioAlta(this IQueryable<IngematicaAngularBase.Model.Entities.Molde> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdUsuarioAlta == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Molde> WithFechaAlta(this IQueryable<IngematicaAngularBase.Model.Entities.Molde> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.FechaAlta == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Molde> WithFechaAltaBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.Molde> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaAlta >= lower);

            if (upper != null)
                range = range.Where(p => p.FechaAlta <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Molde> WithFechaAltaBetween(this IQueryable<IngematicaAngularBase.Model.Entities.Molde> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaAlta >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.FechaAlta < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Molde> WithIdUsuarioModificacion(this IQueryable<IngematicaAngularBase.Model.Entities.Molde> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdUsuarioModificacion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Molde> WithFechaModificacion(this IQueryable<IngematicaAngularBase.Model.Entities.Molde> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.FechaModificacion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Molde> WithFechaModificacionBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.Molde> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaModificacion >= lower);

            if (upper != null)
                range = range.Where(p => p.FechaModificacion <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Molde> WithFechaModificacionBetween(this IQueryable<IngematicaAngularBase.Model.Entities.Molde> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaModificacion >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.FechaModificacion < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Molde> WithIdTipoMedida(this IQueryable<IngematicaAngularBase.Model.Entities.Molde> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdTipoMedida == value);
			
			return source;
		}
	}
}
