//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class PedidoProductoProcesoSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.PedidoProductoProceso> WithIdPedidoProductoProceso(this IQueryable<IngematicaAngularBase.Model.Entities.PedidoProductoProceso> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdPedidoProductoProceso == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.PedidoProductoProceso> WithIdProceso(this IQueryable<IngematicaAngularBase.Model.Entities.PedidoProductoProceso> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdProceso == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.PedidoProductoProceso> WithIdProgramacionPedidoProducto(this IQueryable<IngematicaAngularBase.Model.Entities.PedidoProductoProceso> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdProgramacionPedidoProducto == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.PedidoProductoProceso> WithCantidad(this IQueryable<IngematicaAngularBase.Model.Entities.PedidoProductoProceso> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.Cantidad == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.PedidoProductoProceso> WithScrap(this IQueryable<IngematicaAngularBase.Model.Entities.PedidoProductoProceso> source, decimal? value)
		{
			if (value != null)
				return source.Where(p => p.Scrap == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.PedidoProductoProceso> WithIdPedidoProductoMedida(this IQueryable<IngematicaAngularBase.Model.Entities.PedidoProductoProceso> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdPedidoProductoMedida == value);
			
			return source;
		}
	}
}
