//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class PedidoEstadoProcesoSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.PedidoEstadoProceso> WithIdPedidoEstadoProceso(this IQueryable<IngematicaAngularBase.Model.Entities.PedidoEstadoProceso> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdPedidoEstadoProceso == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.PedidoEstadoProceso> WithIdPedidoEstado(this IQueryable<IngematicaAngularBase.Model.Entities.PedidoEstadoProceso> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdPedidoEstado == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.PedidoEstadoProceso> WithIdProceso(this IQueryable<IngematicaAngularBase.Model.Entities.PedidoEstadoProceso> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdProceso == value);
			
			return source;
		}
	}
}
