//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class PedidoProductoMedidaEstadoSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.PedidoProductoMedidaEstado> WithIdPedidoProductoMedidaEstado(this IQueryable<IngematicaAngularBase.Model.Entities.PedidoProductoMedidaEstado> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdPedidoProductoMedidaEstado == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.PedidoProductoMedidaEstado> WithIdPedidoProductoMedida(this IQueryable<IngematicaAngularBase.Model.Entities.PedidoProductoMedidaEstado> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdPedidoProductoMedida == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.PedidoProductoMedidaEstado> WithIdPedidoEstado(this IQueryable<IngematicaAngularBase.Model.Entities.PedidoProductoMedidaEstado> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdPedidoEstado == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.PedidoProductoMedidaEstado> WithCantidad(this IQueryable<IngematicaAngularBase.Model.Entities.PedidoProductoMedidaEstado> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.Cantidad == value);
			
			return source;
		}
	}
}
