//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class ProductoInsertoSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.ProductoInserto> WithIdProductoInserto(this IQueryable<IngematicaAngularBase.Model.Entities.ProductoInserto> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdProductoInserto == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.ProductoInserto> WithIdProducto(this IQueryable<IngematicaAngularBase.Model.Entities.ProductoInserto> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdProducto == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.ProductoInserto> WithIdInserto(this IQueryable<IngematicaAngularBase.Model.Entities.ProductoInserto> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdInserto == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.ProductoInserto> WithCantidad(this IQueryable<IngematicaAngularBase.Model.Entities.ProductoInserto> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.Cantidad == value);
			
			return source;
		}
	}
}
