//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class ProductoMaterialSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.ProductoMaterial> WithIdProductoMaterial(this IQueryable<IngematicaAngularBase.Model.Entities.ProductoMaterial> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdProductoMaterial == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.ProductoMaterial> WithIdProducto(this IQueryable<IngematicaAngularBase.Model.Entities.ProductoMaterial> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdProducto == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.ProductoMaterial> WithIdMaterial(this IQueryable<IngematicaAngularBase.Model.Entities.ProductoMaterial> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdMaterial == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.ProductoMaterial> WithIdColor(this IQueryable<IngematicaAngularBase.Model.Entities.ProductoMaterial> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdColor == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.ProductoMaterial> WithPeso(this IQueryable<IngematicaAngularBase.Model.Entities.ProductoMaterial> source, decimal? value)
		{
			if (value != null)
				return source.Where(p => p.Peso == value);
			
			return source;
		}
	}
}
