//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class ProveedorSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> WithIdProveedor(this IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdProveedor == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> WithNombre(this IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Nombre == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> WithContainsNombre(this IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Nombre.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> WithEmail(this IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Email == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> WithContainsEmail(this IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Email.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> WithTelefono(this IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Telefono == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> WithContainsTelefono(this IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Telefono.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> WithIdLocalidad(this IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdLocalidad == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> WithDireccion(this IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Direccion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> WithContainsDireccion(this IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Direccion.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> WithIdUsuarioAlta(this IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdUsuarioAlta == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> WithFechaAlta(this IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.FechaAlta == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> WithFechaAltaBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaAlta >= lower);

            if (upper != null)
                range = range.Where(p => p.FechaAlta <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> WithFechaAltaBetween(this IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaAlta >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.FechaAlta < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> WithIdUsuarioModificacion(this IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdUsuarioModificacion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> WithFechaModificacion(this IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.FechaModificacion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> WithFechaModificacionBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaModificacion >= lower);

            if (upper != null)
                range = range.Where(p => p.FechaModificacion <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> WithFechaModificacionBetween(this IQueryable<IngematicaAngularBase.Model.Entities.Proveedor> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaModificacion >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.FechaModificacion < upper);
			}

            return range;
		}

	}
}
