//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class PuntoVentaSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.PuntoVenta> WithIdPuntoVenta(this IQueryable<IngematicaAngularBase.Model.Entities.PuntoVenta> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdPuntoVenta == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.PuntoVenta> WithNumero(this IQueryable<IngematicaAngularBase.Model.Entities.PuntoVenta> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.Numero == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.PuntoVenta> WithIdEmpresa(this IQueryable<IngematicaAngularBase.Model.Entities.PuntoVenta> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdEmpresa == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.PuntoVenta> WithActivo(this IQueryable<IngematicaAngularBase.Model.Entities.PuntoVenta> source, bool? value)
		{
			if (value != null)
				return source.Where(p => p.Activo == value);
			
			return source;
		}
	}
}
