//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class ReinyeccionSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.Reinyeccion> WithIdReinyeccion(this IQueryable<IngematicaAngularBase.Model.Entities.Reinyeccion> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdReinyeccion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Reinyeccion> WithIdPedidoProductoMedida(this IQueryable<IngematicaAngularBase.Model.Entities.Reinyeccion> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdPedidoProductoMedida == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Reinyeccion> WithIdProceso(this IQueryable<IngematicaAngularBase.Model.Entities.Reinyeccion> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdProceso == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Reinyeccion> WithFecha(this IQueryable<IngematicaAngularBase.Model.Entities.Reinyeccion> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.Fecha == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Reinyeccion> WithFechaBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.Reinyeccion> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.Fecha >= lower);

            if (upper != null)
                range = range.Where(p => p.Fecha <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Reinyeccion> WithFechaBetween(this IQueryable<IngematicaAngularBase.Model.Entities.Reinyeccion> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.Fecha >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.Fecha < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Reinyeccion> WithCantidad(this IQueryable<IngematicaAngularBase.Model.Entities.Reinyeccion> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.Cantidad == value);
			
			return source;
		}
	}
}
