//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class RolReglaSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.RolRegla> WithIdRolRegla(this IQueryable<IngematicaAngularBase.Model.Entities.RolRegla> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdRolRegla == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.RolRegla> WithIdRegla(this IQueryable<IngematicaAngularBase.Model.Entities.RolRegla> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdRegla == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.RolRegla> WithIdRol(this IQueryable<IngematicaAngularBase.Model.Entities.RolRegla> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdRol == value);
			
			return source;
		}
	}
}
