//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class SecurityRefreshTokenSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> WithIdSecurityRefreshToken(this IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdSecurityRefreshToken == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> WithToken(this IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Token == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> WithContainsToken(this IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Token.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> WithUsername(this IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Username == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> WithContainsUsername(this IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Username.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> WithClientId(this IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> source, string value)
		{
			if (value != null)
				return source.Where(p => p.ClientId == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> WithContainsClientId(this IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> source, string value)
		{
			if (value != null)
				return source.Where(p => p.ClientId.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> WithIssuedUtc(this IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.IssuedUtc == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> WithIssuedUtcBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.IssuedUtc >= lower);

            if (upper != null)
                range = range.Where(p => p.IssuedUtc <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> WithIssuedUtcBetween(this IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.IssuedUtc >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.IssuedUtc < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> WithExpiresUtc(this IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.ExpiresUtc == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> WithExpiresUtcBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.ExpiresUtc >= lower);

            if (upper != null)
                range = range.Where(p => p.ExpiresUtc <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> WithExpiresUtcBetween(this IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.ExpiresUtc >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.ExpiresUtc < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> WithProtectedTicket(this IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> source, string value)
		{
			if (value != null)
				return source.Where(p => p.ProtectedTicket == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> WithContainsProtectedTicket(this IQueryable<IngematicaAngularBase.Model.Entities.SecurityRefreshToken> source, string value)
		{
			if (value != null)
				return source.Where(p => p.ProtectedTicket.Contains(value));
			
			return source;
		}

	}
}
