//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class sysdiagramsSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.sysdiagrams> Withname(this IQueryable<IngematicaAngularBase.Model.Entities.sysdiagrams> source, string value)
		{
			if (value != null)
				return source.Where(p => p.name == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.sysdiagrams> WithContainsname(this IQueryable<IngematicaAngularBase.Model.Entities.sysdiagrams> source, string value)
		{
			if (value != null)
				return source.Where(p => p.name.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.sysdiagrams> Withprincipal_id(this IQueryable<IngematicaAngularBase.Model.Entities.sysdiagrams> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.principal_id == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.sysdiagrams> Withdiagram_id(this IQueryable<IngematicaAngularBase.Model.Entities.sysdiagrams> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.diagram_id == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.sysdiagrams> Withversion(this IQueryable<IngematicaAngularBase.Model.Entities.sysdiagrams> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.version == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.sysdiagrams> Withdefinition(this IQueryable<IngematicaAngularBase.Model.Entities.sysdiagrams> source, byte[] value)
		{
			if (value != null)
				return source.Where(p => p.definition == value);
			
			return source;
		}
	}
}
