//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class UserLogSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.UserLog> WithIdUserLog(this IQueryable<IngematicaAngularBase.Model.Entities.UserLog> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdUserLog == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.UserLog> WithUsuario(this IQueryable<IngematicaAngularBase.Model.Entities.UserLog> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Usuario == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.UserLog> WithContainsUsuario(this IQueryable<IngematicaAngularBase.Model.Entities.UserLog> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Usuario.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.UserLog> WithDescripcion(this IQueryable<IngematicaAngularBase.Model.Entities.UserLog> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Descripcion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.UserLog> WithContainsDescripcion(this IQueryable<IngematicaAngularBase.Model.Entities.UserLog> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Descripcion.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.UserLog> WithFecha(this IQueryable<IngematicaAngularBase.Model.Entities.UserLog> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.Fecha == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.UserLog> WithFechaBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.UserLog> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.Fecha >= lower);

            if (upper != null)
                range = range.Where(p => p.Fecha <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.UserLog> WithFechaBetween(this IQueryable<IngematicaAngularBase.Model.Entities.UserLog> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.Fecha >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.Fecha < upper);
			}

            return range;
		}

	}
}
