//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <responsibility>
//     Especification Pattern used in the Data Layer to filter the sets of
//     data entities.
// </responsibility>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Linq;

namespace IngematicaAngularBase.Dal.Specification
{
	public static partial class UsuarioSpecification
	{
		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithIdUsuario(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdUsuario == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithNombreUsuario(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, string value)
		{
			if (value != null)
				return source.Where(p => p.NombreUsuario == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithContainsNombreUsuario(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, string value)
		{
			if (value != null)
				return source.Where(p => p.NombreUsuario.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithFechaAlta(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.FechaAlta == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithFechaAltaBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaAlta >= lower);

            if (upper != null)
                range = range.Where(p => p.FechaAlta <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithFechaAltaBetween(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaAlta >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.FechaAlta < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithFechaModificacion(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.FechaModificacion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithFechaModificacionBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaModificacion >= lower);

            if (upper != null)
                range = range.Where(p => p.FechaModificacion <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithFechaModificacionBetween(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.FechaModificacion >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.FechaModificacion < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithNombre(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Nombre == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithContainsNombre(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Nombre.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithApellido(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Apellido == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithContainsApellido(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Apellido.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithActivo(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, bool? value)
		{
			if (value != null)
				return source.Where(p => p.Activo == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithEmail(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Email == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithContainsEmail(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Email.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithPassword(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Password == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithContainsPassword(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, string value)
		{
			if (value != null)
				return source.Where(p => p.Password.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithPasswordSalt(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, string value)
		{
			if (value != null)
				return source.Where(p => p.PasswordSalt == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithContainsPasswordSalt(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, string value)
		{
			if (value != null)
				return source.Where(p => p.PasswordSalt.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithIdRol(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdRol == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithResetPasswordGuid(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, string value)
		{
			if (value != null)
				return source.Where(p => p.ResetPasswordGuid == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithContainsResetPasswordGuid(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, string value)
		{
			if (value != null)
				return source.Where(p => p.ResetPasswordGuid.Contains(value));
			
			return source;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithResetPasswordFecha(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, System.DateTime? value)
		{
			if (value != null)
				return source.Where(p => p.ResetPasswordFecha == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithResetPasswordFechaBetweenWithTime(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.ResetPasswordFecha >= lower);

            if (upper != null)
                range = range.Where(p => p.ResetPasswordFecha <= upper);

            return range;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithResetPasswordFechaBetween(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, System.DateTime? lower, System.DateTime? upper)
		{
            var range = source;
           
            if (lower != null)
                range = range.Where(p => p.ResetPasswordFecha >= lower);

            if (upper != null)
			{
				upper = upper.Value.Date.AddDays(1);
                range = range.Where(p => p.ResetPasswordFecha < upper);
			}

            return range;
		}


		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithIdUsuarioAlta(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdUsuarioAlta == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithIdUsuarioModificacion(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, int? value)
		{
			if (value != null)
				return source.Where(p => p.IdUsuarioModificacion == value);
			
			return source;
		}

		public static IQueryable<IngematicaAngularBase.Model.Entities.Usuario> WithInterno(this IQueryable<IngematicaAngularBase.Model.Entities.Usuario> source, bool? value)
		{
			if (value != null)
				return source.Where(p => p.Interno == value);
			
			return source;
		}
	}
}
